include:
  - template: Auto-DevOps.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Auto-DevOps.gitlab-ci.yml

variables:
  SAST_JAVA_VERSION: 11
  POSTGRES_ENABLED: "false"
